# Generated by Django 3.1.12 on 2025-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCapture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(max_length=100)),
                ('pokedex_number', models.IntegerField()),
                ('date_captured', models.DateField(auto_now_add=True)),
                ('is_shiny', models.BooleanField(default=False)),
            ],
        ),
    ]
