# Generated by Django 4.1.13 on 2025-05-19 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_pokemoncapture_previous_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='tradepokemon',
            name='pokemon',
        ),
        migrations.RemoveField(
            model_name='tradepokemon',
            name='trade',
        ),
        migrations.RemoveField(
            model_name='traderequest',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='traderequest',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='pokemoncapture',
            name='previous_owner',
        ),
        migrations.RemoveField(
            model_name='pokemoncapture',
            name='received_via_trade',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='TradePokemon',
        ),
        migrations.DeleteModel(
            name='TradeRequest',
        ),
    ]
